#!/usr/bin/env node
// Генерация src/types.ts из OpenAPI-спеки клиентского API.
//
//   npm run gen                       # docs/openapi/vdsok-client-api-v1.yaml из репо биллинга
//   npm run gen -- path/to/spec.yaml  # любой другой файл
//   VDSOK_OPENAPI=https://vdsok.guru/api/v1/openapi.json npm run gen
//
// Почему не `openapi-typescript spec.yaml` напрямую: авторская YAML-спека
// использует якоря и merge-ключи (`<<: *ErrAuth`) в блоке `x-shared`, а
// парсер YAML 1.2 внутри openapi-typescript merge-ключи не разворачивает —
// в типах появились бы ответы с ключом "<<". Поэтому читаем YAML сами с
// `merge: true`, выбрасываем `x-shared` (как делает build_openapi.py на
// бэкенде) и отдаём генератору уже развёрнутый объект.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const defaultSpec = resolve(pkgRoot, "..", "..", "docs", "openapi", "vdsok-client-api-v1.yaml");
const source = process.argv[2] || process.env.VDSOK_OPENAPI || defaultSpec;

async function loadSchema(src) {
  if (/^https?:\/\//.test(src)) {
    const res = await fetch(src, { headers: { Accept: "application/json" } });
    if (!res.ok) throw new Error(`GET ${src} → HTTP ${res.status}`);
    return await res.json();
  }
  if (!existsSync(src)) {
    throw new Error(
      `Spec not found: ${src}\n` +
        "Pass a path/URL as the first argument or set VDSOK_OPENAPI " +
        "(e.g. https://vdsok.guru/api/v1/openapi.json).",
    );
  }
  const text = readFileSync(src, "utf8");
  // maxAliasCount: по умолчанию 100 — защита от billion-laughs; у нас ~70
  // операций по 5–10 якорей каждая, лимит снимаем для доверенного файла.
  return src.endsWith(".json")
    ? JSON.parse(text)
    : parseYaml(text, { merge: true, maxAliasCount: -1 });
}

const schema = await loadSchema(source);
delete schema["x-shared"];

// Примеры из спеки в типах становятся только JSDoc-комментариями, а в них
// попадают реальные адреса и логины с прода (спека документирует живую
// систему). sdk_export.py отказывается публиковать такие файлы, поэтому
// примеры вырезаем целиком до генерации — типам они не нужны.
function stripExamples(node) {
  if (Array.isArray(node)) {
    for (const item of node) stripExamples(item);
  } else if (node && typeof node === "object") {
    delete node.example;
    delete node.examples;
    for (const value of Object.values(node)) stripExamples(value);
  }
}
stripExamples(schema);

const ast = await openapiTS(schema, {
  // Чистые `type` алиасы вместо interface: они лучше сливаются в allOf
  // (ServerDetail = Server & {...}) и не тянут declaration merging.
  exportType: true,
  alphabetize: false,
  // enum'ы оставляем строковыми union-типами: пользователю не нужен рантайм.
  enum: false,
  // Поле с `default` в теле запроса (ServerCreate.months = 1) должно
  // оставаться необязательным для вызывающего — сервер подставит значение сам.
  defaultNonNullable: false,
});

const header =
  "// Generated by scripts/gen.mjs from the VDSok Client API v1 OpenAPI spec.\n" +
  `// Source: ${source.includes("docs/openapi") || source.includes("docs\\openapi") ? "docs/openapi/vdsok-client-api-v1.yaml" : source}\n` +
  "// Do not edit by hand — run `npm run gen`.\n" +
  "/* eslint-disable */\n\n";

const out = resolve(pkgRoot, "src", "types.ts");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, header + astToString(ast), "utf8");
console.log(`types → ${out} (${schema.info?.title} ${schema.info?.version})`);
